---
- name: run bundle install (this will take few minutes)
  command: >
    bundle install {{ redmine_bundle_install_opts }}
    chdir={{ redmine_base_dir }}

- name: generate secret token
  shell: >
    bundle exec rake generate_secret_token RAILS_ENV=production
    chdir={{ redmine_base_dir }}

- name: initialize database
  shell: >
    bundle exec rake db:migrate RAILS_ENV=production
    chdir={{ redmine_base_dir }}

- name: load default data set
  shell: >
    bundle exec rake redmine:load_default_data RAILS_ENV=production REDMINE_LANG={{ redmine_lang }}
    chdir={{ redmine_base_dir }}
